SPOOL /Users/maywzh/Workspace/ji_coursenotes/2020summer/CSCI835/assignment/assignment3/src/solution2_con2.lst
SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 100
SET PAGESIZE 200
SET SERVEROUTPUT ON

UPDATE ORDERS
SET EMPLOYEE_ID=3
WHERE ORDER_ID=310;

UPDATE ORDERS
SET EMPLOYEE_ID=7
WHERE ORDER_ID=308;
