SPOOL /Users/maywzh/Workspace/ji_coursenotes/2020summer/CSCI835/assignment/assignment3/src/solution2_con1.lst
SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 100
SET PAGESIZE 200
SET SERVEROUTPUT ON

UPDATE ORDERS
SET EMPLOYEE_ID=4
WHERE ORDER_ID=308;

UPDATE ORDERS
SET EMPLOYEE_ID=2
WHERE ORDER_ID=310;