set echo on
set feedback on
set linesize 300

spool dbdrop

DROP TABLE ORDER_DETAIL;
DROP TABLE ORDERS;
DROP TABLE PRODUCT;
DROP TABLE SUPPLIER;
DROP TABLE CATEGORY;
DROP TABLE CUSTOMER;
DROP TABLE EMPLOYEE;
DROP TABLE SHIPPER;

spool off
