EXPLAIN PLAN FOR SELECT ORDER_ID, ORDER_DATE FROM ORDERS;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

CREATE INDEX ORDERS_IDX ON ORDERS(ORDER_ID, ORDER_DATE);
EXPLAIN PLAN FOR SELECT ORDER_ID, ORDER_DATE FROM ORDERS;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);
DROP INDEX ORDERS_IDX;