SPOOL /Users/maywzh/Workspace/ji_coursenotes/2020summer/CSCI835/assignment/assignment2/src/solution3.lst
SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 100
SET PAGESIZE 200
SET SERVEROUTPUT ON

SELECT * FROM ORDER_DETAIL WHERE PRODUCT_NAME = 'BOLT' AND QUANTITY > 100;

SELECT DISTINCT CATEGORY_NAME FROM PRODUCT;

SELECT UNIT_PRICE FROM ORDER_DETAIL WHERE QUANTITY IN (100, 200, 300) OR DISCOUNT = 0.01;

SELECT CATEGORY_NAME, SUPPLIER_NAME, COUNT(*) FROM PRODUCT GROUP BY CATEGORY_NAME, SUPPLIER_NAME;

SELECT SUPPLIER_NAME, UNIT_PRICE FROM PRODUCT ORDER BY UNIT_PRICE, QUANTITY_PER_UNIT;

SELECT SUPPLIER.COMPANY_NAME, SUPPLIER.CITY FROM PRODUCT JOIN SUPPLIER ON PRODUCT.SUPPLIER_NAME = SUPPLIER.COMPANY_NAME;

SPOOL OFF