SPOOL /Users/maywzh/Workspace/ji_coursenotes/2020summer/CSCI835/assignment/assignment2/src/solution1.lst
SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 100
SET PAGESIZE 200
SET SERVEROUTPUT ON

EXPLAIN PLAN FOR SELECT * FROM ORDER_DETAIL WHERE PRODUCT_NAME = 'BOLT' AND QUANTITY > 100;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

EXPLAIN PLAN FOR SELECT DISTINCT CATEGORY_NAME FROM PRODUCT;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

EXPLAIN PLAN FOR SELECT UNIT_PRICE FROM ORDER_DETAIL WHERE QUANTITY IN (100, 200, 300) OR DISCOUNT = 0.01;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

EXPLAIN PLAN FOR SELECT CATEGORY_NAME, SUPPLIER_NAME, COUNT(*) FROM PRODUCT GROUP BY CATEGORY_NAME, SUPPLIER_NAME;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

EXPLAIN PLAN FOR SELECT SUPPLIER_NAME, UNIT_PRICE FROM PRODUCT ORDER BY UNIT_PRICE, QUANTITY_PER_UNIT;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

EXPLAIN PLAN FOR SELECT SUPPLIER.COMPANY_NAME, SUPPLIER.CITY FROM PRODUCT JOIN SUPPLIER ON PRODUCT.SUPPLIER_NAME = SUPPLIER.COMPANY_NAME;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

CREATE INDEX PNQ_IDX ON ORDER_DETAIL(PRODUCT_NAME, QUANTITY);
EXPLAIN PLAN FOR SELECT * FROM ORDER_DETAIL WHERE PRODUCT_NAME = 'BOLT' AND QUANTITY > 100;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

CREATE INDEX CN_IDX ON PRODUCT(CATEGORY_NAME);
EXPLAIN PLAN FOR SELECT DISTINCT CATEGORY_NAME FROM PRODUCT;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

CREATE INDEX DISCOUNT_IDX ON ORDER_DETAIL(DISCOUNT);
CREATE INDEX QUANTITY_IDX ON ORDER_DETAIL(QUANTITY);
EXPLAIN PLAN FOR SELECT UNIT_PRICE FROM ORDER_DETAIL WHERE QUANTITY IN (100, 200, 300) OR DISCOUNT = 0.01;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

CREATE INDEX CATE_SN_IDX ON PRODUCT(CATEGORY_NAME, SUPPLIER_NAME);
EXPLAIN PLAN FOR SELECT CATEGORY_NAME, SUPPLIER_NAME, COUNT(*) FROM PRODUCT GROUP BY CATEGORY_NAME, SUPPLIER_NAME;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

CREATE INDEX UP_QPU_IDX ON PRODUCT(UNIT_PRICE, QUANTITY_PER_UNIT, SUPPLIER_NAME);
EXPLAIN PLAN FOR SELECT SUPPLIER_NAME, UNIT_PRICE FROM PRODUCT ORDER BY UNIT_PRICE, QUANTITY_PER_UNIT;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

CREATE INDEX SN_IDX ON PRODUCT(SUPPLIER_NAME);
CREATE INDEX SUP_CY_IDX ON SUPPLIER(COMPANY_NAME, CITY);
EXPLAIN PLAN FOR SELECT SUPPLIER.COMPANY_NAME, SUPPLIER.CITY FROM PRODUCT JOIN SUPPLIER ON PRODUCT.SUPPLIER_NAME = SUPPLIER.COMPANY_NAME;
SELECT * FROM TABLE(DBMS_XPLAN.DISPLAY);

DROP INDEX PNQ_IDX;
DROP INDEX CN_IDX;
DROP INDEX QUANTITY_IDX; 
DROP INDEX DISCOUNT_IDX;
DROP INDEX CATE_SN_IDX;
DROP INDEX UP_QPU_IDX;
DROP INDEX SN_IDX;
DROP INDEX SUP_CY_IDX;

SPOOL OFF