SPOOL /Users/maywzh/Workspace/ji_coursenotes/2020summer/CSCI835/assignment/assignment2/src/solution3.lst
SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 100
SET PAGESIZE 200
SET SERVEROUTPUT ON

ALTER TABLE PRODUCT
ADD ORDERED_NUM NUMBER(9) DEFAULT 0;

UPDATE PRODUCT p SET ORDERED_NUM = nvl((SELECT sum(QUANTITY) AS sumnum FROM ORDER_DETAIL od GROUP BY od.PRODUCT_NAME HAVING od.PRODUCT_NAME = p.PRODUCT_NAME), 0);

CREATE OR REPLACE TRIGGER OrderProduct 
AFTER INSERT ON ORDER_DETAIL
FOR EACH ROW
WHEN (NEW.QUANTITY > 0)
BEGIN
  UPDATE PRODUCT p SET ORDERED_NUM = ORDERED_NUM + :NEW.QUANTITY WHERE p.PRODUCT_NAME = :NEW.PRODUCT_NAME;
END;
/

SELECT ORDERED_NUM FROM PRODUCT WHERE PRODUCT_NAME = 'Lakkalikoori';
INSERT INTO ORDER_DETAIL VALUES(383, 'Lakkalikoori', 16.2, 10, 0.1);
SELECT ORDERED_NUM FROM PRODUCT WHERE PRODUCT_NAME = 'Lakkalikoori';

SELECT ORDERED_NUM FROM PRODUCT WHERE PRODUCT_NAME = 'Chartreuse verte';
INSERT INTO ORDER_DETAIL VALUES(383, 'Chartreuse verte', 102.1, 15, 0.2);
SELECT ORDERED_NUM FROM PRODUCT WHERE PRODUCT_NAME = 'Chartreuse verte';



SPOOL OFF