SPOOL /Users/maywzh/Workspace/ji_coursenotes/2020summer/CSCI835/assignment/assignment2/src/solution3.lst
SET ECHO ON
SET FEEDBACK ON
SET LINESIZE 100
SET PAGESIZE 200
SET SERVEROUTPUT ON

ALTER TABLE PRODUCT
ADD ORDERED_NUM NUMBER(9) DEFAULT 0;

UPDATE PRODUCT p SET ORDERED_NUM = nvl((SELECT sum(QUANTITY) AS sumnum FROM ORDER_DETAIL od GROUP BY od.PRODUCT_NAME HAVING od.PRODUCT_NAME = p.PRODUCT_NAME), 0);

ALTER TABLE PRODUCT
DROP COLUMN ORDERED_NUM;

CREATE TRIGGER OrderProduct 
  AFTER INSERT ON ORDER_DETAIL
  BEGIN
    UPDATE PRODUCT p SET ORDERED_NUM = ORDERED_NUM + :NEW.QUANTITY WHERE p.PRODUCT_NAME = :NEW.PRODUCT_NAME;
    
  END 
  

BEFORE 

END

SPOOL OFF